import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";
import { ToastContainer } from 'react-toastify';

const OutfitFont=Outfit({
  subsets:["latin"]
})



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={` h-full antialiased`}
    >
      <body className={`${OutfitFont.className} min-h-full flex flex-col`}>
        <Navbar/>
        <main>

        {children}
         <ToastContainer position="top-center"/>
        </main>
        <Footer/>
        </body>
    </html>
  );
}
